# spring.profiles.activeにデフォルトでアクティブなプロファイルを指定
spring:
  profiles:
    active: dev

# "---"でプロファイルを区切る
# プロファイル名はspring.profilesに書く
---
spring:
  profiles: dev
salesforce :
  user : techdev.force@gmail.com
  password : techdev1
  token :
proxyserver :
  name : 
  port : 80
mybatis :
  env : 

---
spring:
  profiles: production
salesforce :
  user : "kkamemur@nikkeibp.co.jp"
  password : kamemura1
  token :
proxyserver :
  name : 
  port : 
mybatis :
  env : 


